run:
  tests: false
  skip-dirs:
    - pkg

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    # - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    # - wsl
    - nolintlint

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - golint
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: "ST1003:"
      linters:
        - stylecheck
    # TODO: Remove these when we are ready to drop support for Legacy Amino
    - text: "SA1019: codec.LegacyAmino is deprecated"
      linters:
        - staticcheck
    - text: "SA1019: legacybech32.UnmarshalPubKey is deprecated"
      linters:
        - staticcheck
    - text: "SA1019: package github.com/cosmos/cosmos-sdk/types/bech32/legacybech32 is deprecated"
      linters:
        - staticcheck

    # TODO: Remove this once we have implemented expected_keepers for all the modules
    - text: "`bk` can be `github.com/cosmos/cosmos-sdk/x/simulation.BankKeeper`"
      linters:
        - interfacer
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
