FROM node:alpine

WORKDIR /root

# Install ts-relayer
RUN npm install -g @confio/relayer

# Install bash
RUN apk add --no-cache bash

COPY ./scripts/relayer-config ./.ibc-setup
COPY ./scripts/setup-tsrelayer.sh .