package types

// DONTCOVER

const (
	EventTypeSavedProfile   = "saved_profile"
	EventTypeDeletedProfile = "deleted_profile"

	EventTypeRequestedDTagTransferRequest     = "created_dtag_transfer_request"
	EventTypeAcceptedDTagTransferRequest      = "accepted_dtag_transfer_request"
	EventTypeRefusedDTagTransferRequest       = "refused_dtag_transfer_request"
	EventTypeCanceledDTagTransferRequest      = "canceled_dtag_transfer_request"
	EventTypeCreatedChainLink                 = "created_chain_link"
	EventTypeDeletedChainLink                 = "deleted_chain_link"
	EventTypeSavedChainLink                   = "saved_chain_link"
	EventTypeSetDefaultExternalAddress        = "set_default_external_address"
	EventTypeCreatedApplicationLink           = "created_application_link"
	EventTypeDeletedApplicationLink           = "deleted_application_link"
	EventTypeSavedApplicationLink             = "saved_application_link"
	EventTypeReceivedLinkChainAccountPacket   = "received_link_chain_account_packet"
	EventTypeReceivedOracleResponsePacketData = "received_oracle_response_packet"
	EventTypeTimeout                          = "timeout"

	AttributeKeyProfileDTag                   = "profile_dtag"
	AttributeKeyProfileCreator                = "profile_creator"
	AttributeKeyProfileCreationTime           = "profile_creation_time"
	AttributeKeyRequestReceiver               = "request_receiver"
	AttributeKeyRequestSender                 = "request_sender"
	AttributeKeyDTagToTrade                   = "dtag_to_trade"
	AttributeKeyNewDTag                       = "new_dtag"
	AttributeKeyChainLinkExternalAddress      = "chain_link_external_address"
	AttributeKeyChainLinkOwner                = "chain_link_owner"
	AttributeKeyChainLinkChainName            = "chain_link_chain_name"
	AttributeKeyChainLinkCreationTime         = "chain_link_creation_time"
	AttributeKeyApplicationLinkExpirationTime = "application_link_expiration_time"
	AttributeKeyAckSuccess                    = "success"
	AttributeKeyUser                          = "user"
	AttributeKeyApplicationName               = "application_name"
	AttributeKeyApplicationUsername           = "application_username"
	AttributeKeyApplicationLinkCreationTime   = "application_link_creation_time"
	AttributeKeyOracleID                      = "oracle_id"
	AttributeKeyClientID                      = "client_id"
	AttributeKeyRequestID                     = "request_id"
	AttributeKeyResolveStatus                 = "resolve_status"
	AttributeKeyAck                           = "acknowledgement"
	AttributeKeyAckError                      = "error"
)
