// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: desmos/profiles/v3/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("desmos/profiles/v3/query.proto", fileDescriptor_bcbdebc2a1cf2f2b) }

var fileDescriptor_bcbdebc2a1cf2f2b = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0x3f, 0xf8, 0x55, 0x18, 0x04, 0xe5, 0x01, 0x41, 0x43, 0xdc, 0x62, 0x35, 0x7f,
	0x48, 0xb3, 0xbb, 0x4d, 0x43, 0x8b, 0x11, 0x3d, 0xb4, 0x8d, 0x87, 0xa2, 0x60, 0x95, 0x9e, 0xbc,
	0x84, 0x49, 0x32, 0xd9, 0x2e, 0x6e, 0x66, 0xb6, 0x3b, 0x9b, 0xd8, 0x50, 0x72, 0xf1, 0xe6, 0xa5,
	0x08, 0xde, 0x3d, 0xf9, 0x12, 0x7c, 0x0f, 0x7a, 0x11, 0x0b, 0x5e, 0x3c, 0x4a, 0xe2, 0x0b, 0x91,
	0xcc, 0xce, 0x24, 0x1a, 0x77, 0x92, 0x34, 0xb7, 0x25, 0xf3, 0xfd, 0x3e, 0xcf, 0xe7, 0x3b, 0xcf,
	0xc3, 0x04, 0x99, 0x4d, 0xc2, 0xdb, 0x8c, 0x3b, 0x41, 0xc8, 0x5a, 0x9e, 0x4f, 0xb8, 0xd3, 0x2d,
	0x3b, 0x27, 0x1d, 0x12, 0xf6, 0xec, 0x20, 0x64, 0x11, 0x03, 0x88, 0xcf, 0x6d, 0x75, 0x6e, 0x77,
	0xcb, 0xa9, 0xb4, 0xcb, 0x98, 0xeb, 0x13, 0x07, 0x07, 0x9e, 0x83, 0x29, 0x65, 0x11, 0x8e, 0x3c,
	0x46, 0x79, 0xec, 0x48, 0x65, 0x75, 0x15, 0x6b, 0xf2, 0x17, 0xa9, 0x2b, 0x6a, 0x75, 0xcd, 0x08,
	0xbb, 0xb5, 0x90, 0x9c, 0x74, 0x08, 0x8f, 0x54, 0xd5, 0x8c, 0xbe, 0x2a, 0x0e, 0x71, 0x5b, 0xc9,
	0x0a, 0x5a, 0x59, 0xe3, 0x18, 0x7b, 0xb4, 0xe6, 0x7b, 0xf4, 0x95, 0xd2, 0xe6, 0xb5, 0x5a, 0x1c,
	0x04, 0x7f, 0x2a, 0xb7, 0xce, 0xaf, 0xa2, 0xff, 0x9f, 0x8f, 0x4e, 0xe0, 0xad, 0x81, 0xae, 0x1c,
	0xc6, 0x7a, 0xc8, 0xd9, 0xff, 0xde, 0x8d, 0x2d, 0x64, 0x52, 0xf1, 0x22, 0x8e, 0x90, 0xca, 0xcf,
	0x17, 0xf2, 0x80, 0x51, 0x4e, 0xd6, 0x37, 0xde, 0x7c, 0xff, 0xf5, 0xfe, 0xbf, 0x0c, 0xdc, 0x75,
	0x12, 0xd8, 0xc6, 0xdf, 0x67, 0x1d, 0x4e, 0xc2, 0x3e, 0x7c, 0x33, 0x50, 0xfa, 0x80, 0x36, 0x58,
	0xdb, 0xa3, 0x6e, 0xf5, 0x08, 0xbb, 0x47, 0x21, 0xa6, 0xbc, 0x45, 0x42, 0xd9, 0x96, 0xc3, 0x43,
	0x6d, 0xdf, 0x59, 0x36, 0x45, 0xfd, 0x68, 0x49, 0xb7, 0x8c, 0xb2, 0x25, 0xa2, 0x14, 0xa1, 0x90,
	0x14, 0x65, 0x34, 0x61, 0x2b, 0x92, 0x56, 0x4b, 0x8d, 0x1a, 0xce, 0x0d, 0x84, 0xf6, 0x47, 0x73,
	0x7a, 0x3a, 0xba, 0x7c, 0x28, 0x68, 0x09, 0x26, 0x22, 0x45, 0xbb, 0xb1, 0x90, 0x56, 0xb2, 0xe5,
	0x04, 0xdb, 0x1d, 0x58, 0x4b, 0x62, 0x13, 0x8b, 0x62, 0x89, 0xf1, 0xc3, 0x47, 0x03, 0x5d, 0x1b,
	0xfb, 0x9f, 0xbd, 0xa6, 0x24, 0xe4, 0xe0, 0xcc, 0xef, 0x14, 0x2b, 0x15, 0xda, 0xe6, 0xe2, 0x06,
	0xc9, 0x67, 0x0b, 0xbe, 0x3c, 0x64, 0xe7, 0xf0, 0x39, 0x2c, 0x46, 0xfa, 0x6c, 0xa0, 0x9b, 0x55,
	0xd2, 0xc2, 0x1d, 0x3f, 0x7a, 0x7c, 0x1a, 0x91, 0x90, 0x62, 0x7f, 0xb7, 0xd9, 0x0c, 0x09, 0xe7,
	0x84, 0xc3, 0x7d, 0x6d, 0x7b, 0x9d, 0x45, 0x81, 0x57, 0x96, 0x70, 0xca, 0x04, 0x3b, 0x22, 0xc1,
	0x26, 0xd8, 0x89, 0xd3, 0x8f, 0xdd, 0x16, 0x91, 0x76, 0x0b, 0x8f, 0x61, 0x3f, 0x18, 0xe8, 0xfa,
	0x6e, 0x10, 0xf8, 0x5e, 0x43, 0xbc, 0x29, 0xf1, 0x1e, 0xe8, 0x2f, 0x70, 0x5a, 0xaa, 0xc8, 0x4b,
	0x97, 0x70, 0x48, 0xe2, 0x8c, 0x20, 0x5e, 0x83, 0xdb, 0x49, 0xc4, 0x38, 0x08, 0xe4, 0x46, 0x7c,
	0x35, 0xd0, 0xad, 0xa9, 0x1a, 0x7b, 0xbd, 0x7d, 0xdf, 0x23, 0x34, 0x3a, 0xa8, 0x42, 0x65, 0xd1,
	0xbe, 0x13, 0x8f, 0x42, 0x7e, 0xb0, 0x8c, 0x55, 0xb2, 0x57, 0x04, 0x7b, 0x19, 0x4a, 0x33, 0xd9,
	0x9d, 0x86, 0xf0, 0x71, 0xe7, 0x2c, 0xfe, 0xa8, 0x79, 0xcd, 0x3e, 0x7c, 0x32, 0xd0, 0x8d, 0xa9,
	0x06, 0x72, 0xcf, 0xb7, 0x17, 0x05, 0xfa, 0x7b, 0xdb, 0x77, 0x2e, 0x6b, 0x93, 0x19, 0x8a, 0x22,
	0x43, 0x16, 0xee, 0xcd, 0xce, 0x20, 0x37, 0xbe, 0x8f, 0x56, 0x0f, 0xc5, 0xbb, 0x0f, 0x59, 0xfd,
	0xe3, 0x2a, 0x04, 0x8a, 0x2b, 0x37, 0x57, 0x27, 0x41, 0xd6, 0x05, 0x48, 0x1a, 0x52, 0x89, 0x6f,
	0xb0, 0xd0, 0xee, 0x3d, 0xf9, 0x32, 0x30, 0x8d, 0x8b, 0x81, 0x69, 0xfc, 0x1c, 0x98, 0xc6, 0xbb,
	0xa1, 0xb9, 0x72, 0x31, 0x34, 0x57, 0x7e, 0x0c, 0xcd, 0x95, 0x97, 0x25, 0xd7, 0x8b, 0x8e, 0x3b,
	0x75, 0xbb, 0xc1, 0xda, 0xd2, 0x6f, 0xf9, 0xb8, 0xce, 0x55, 0xad, 0xee, 0xb6, 0x73, 0x3a, 0x29,
	0x18, 0xf5, 0x02, 0xc2, 0xeb, 0xab, 0xe2, 0x4f, 0xa6, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x4b,
	0x59, 0x27, 0x33, 0x8b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Profile queries the profile of a specific user given their DTag or address.
	// If the queried user does not have a profile, the returned response will
	// contain a null profile.
	Profile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error)
	// IncomingDTagTransferRequests queries all the DTag transfers requests that
	// have been made towards the user with the given address
	IncomingDTagTransferRequests(ctx context.Context, in *QueryIncomingDTagTransferRequestsRequest, opts ...grpc.CallOption) (*QueryIncomingDTagTransferRequestsResponse, error)
	// ChainLinks queries the chain links associated to the given user, if
	// provided. Otherwise it queries all the chain links stored.
	ChainLinks(ctx context.Context, in *QueryChainLinksRequest, opts ...grpc.CallOption) (*QueryChainLinksResponse, error)
	// ChainLinkOwners queries for the owners of chain links, optionally searching
	// for a specific chain name and external address
	ChainLinkOwners(ctx context.Context, in *QueryChainLinkOwnersRequest, opts ...grpc.CallOption) (*QueryChainLinkOwnersResponse, error)
	// DefaultExternalAddresses queries the default addresses associated to the
	// given user and (optionally) chain name
	DefaultExternalAddresses(ctx context.Context, in *QueryDefaultExternalAddressesRequest, opts ...grpc.CallOption) (*QueryDefaultExternalAddressesResponse, error)
	// ApplicationLinks queries the applications links associated to the given
	// user, if provided. Otherwise, it queries all the application links stored.
	ApplicationLinks(ctx context.Context, in *QueryApplicationLinksRequest, opts ...grpc.CallOption) (*QueryApplicationLinksResponse, error)
	// ApplicationLinkByClientID queries a single application link for a given
	// client id.
	ApplicationLinkByClientID(ctx context.Context, in *QueryApplicationLinkByClientIDRequest, opts ...grpc.CallOption) (*QueryApplicationLinkByClientIDResponse, error)
	// ApplicationLinkOwners queries for the owners of applications links,
	// optionally searching for a specific application and username.
	ApplicationLinkOwners(ctx context.Context, in *QueryApplicationLinkOwnersRequest, opts ...grpc.CallOption) (*QueryApplicationLinkOwnersResponse, error)
	// Params queries the profiles module params
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Profile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error) {
	out := new(QueryProfileResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IncomingDTagTransferRequests(ctx context.Context, in *QueryIncomingDTagTransferRequestsRequest, opts ...grpc.CallOption) (*QueryIncomingDTagTransferRequestsResponse, error) {
	out := new(QueryIncomingDTagTransferRequestsResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/IncomingDTagTransferRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ChainLinks(ctx context.Context, in *QueryChainLinksRequest, opts ...grpc.CallOption) (*QueryChainLinksResponse, error) {
	out := new(QueryChainLinksResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/ChainLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ChainLinkOwners(ctx context.Context, in *QueryChainLinkOwnersRequest, opts ...grpc.CallOption) (*QueryChainLinkOwnersResponse, error) {
	out := new(QueryChainLinkOwnersResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/ChainLinkOwners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DefaultExternalAddresses(ctx context.Context, in *QueryDefaultExternalAddressesRequest, opts ...grpc.CallOption) (*QueryDefaultExternalAddressesResponse, error) {
	out := new(QueryDefaultExternalAddressesResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/DefaultExternalAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApplicationLinks(ctx context.Context, in *QueryApplicationLinksRequest, opts ...grpc.CallOption) (*QueryApplicationLinksResponse, error) {
	out := new(QueryApplicationLinksResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/ApplicationLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApplicationLinkByClientID(ctx context.Context, in *QueryApplicationLinkByClientIDRequest, opts ...grpc.CallOption) (*QueryApplicationLinkByClientIDResponse, error) {
	out := new(QueryApplicationLinkByClientIDResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/ApplicationLinkByClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApplicationLinkOwners(ctx context.Context, in *QueryApplicationLinkOwnersRequest, opts ...grpc.CallOption) (*QueryApplicationLinkOwnersResponse, error) {
	out := new(QueryApplicationLinkOwnersResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/ApplicationLinkOwners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/desmos.profiles.v3.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Profile queries the profile of a specific user given their DTag or address.
	// If the queried user does not have a profile, the returned response will
	// contain a null profile.
	Profile(context.Context, *QueryProfileRequest) (*QueryProfileResponse, error)
	// IncomingDTagTransferRequests queries all the DTag transfers requests that
	// have been made towards the user with the given address
	IncomingDTagTransferRequests(context.Context, *QueryIncomingDTagTransferRequestsRequest) (*QueryIncomingDTagTransferRequestsResponse, error)
	// ChainLinks queries the chain links associated to the given user, if
	// provided. Otherwise it queries all the chain links stored.
	ChainLinks(context.Context, *QueryChainLinksRequest) (*QueryChainLinksResponse, error)
	// ChainLinkOwners queries for the owners of chain links, optionally searching
	// for a specific chain name and external address
	ChainLinkOwners(context.Context, *QueryChainLinkOwnersRequest) (*QueryChainLinkOwnersResponse, error)
	// DefaultExternalAddresses queries the default addresses associated to the
	// given user and (optionally) chain name
	DefaultExternalAddresses(context.Context, *QueryDefaultExternalAddressesRequest) (*QueryDefaultExternalAddressesResponse, error)
	// ApplicationLinks queries the applications links associated to the given
	// user, if provided. Otherwise, it queries all the application links stored.
	ApplicationLinks(context.Context, *QueryApplicationLinksRequest) (*QueryApplicationLinksResponse, error)
	// ApplicationLinkByClientID queries a single application link for a given
	// client id.
	ApplicationLinkByClientID(context.Context, *QueryApplicationLinkByClientIDRequest) (*QueryApplicationLinkByClientIDResponse, error)
	// ApplicationLinkOwners queries for the owners of applications links,
	// optionally searching for a specific application and username.
	ApplicationLinkOwners(context.Context, *QueryApplicationLinkOwnersRequest) (*QueryApplicationLinkOwnersResponse, error)
	// Params queries the profiles module params
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Profile(ctx context.Context, req *QueryProfileRequest) (*QueryProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (*UnimplementedQueryServer) IncomingDTagTransferRequests(ctx context.Context, req *QueryIncomingDTagTransferRequestsRequest) (*QueryIncomingDTagTransferRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncomingDTagTransferRequests not implemented")
}
func (*UnimplementedQueryServer) ChainLinks(ctx context.Context, req *QueryChainLinksRequest) (*QueryChainLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainLinks not implemented")
}
func (*UnimplementedQueryServer) ChainLinkOwners(ctx context.Context, req *QueryChainLinkOwnersRequest) (*QueryChainLinkOwnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainLinkOwners not implemented")
}
func (*UnimplementedQueryServer) DefaultExternalAddresses(ctx context.Context, req *QueryDefaultExternalAddressesRequest) (*QueryDefaultExternalAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultExternalAddresses not implemented")
}
func (*UnimplementedQueryServer) ApplicationLinks(ctx context.Context, req *QueryApplicationLinksRequest) (*QueryApplicationLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplicationLinks not implemented")
}
func (*UnimplementedQueryServer) ApplicationLinkByClientID(ctx context.Context, req *QueryApplicationLinkByClientIDRequest) (*QueryApplicationLinkByClientIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplicationLinkByClientID not implemented")
}
func (*UnimplementedQueryServer) ApplicationLinkOwners(ctx context.Context, req *QueryApplicationLinkOwnersRequest) (*QueryApplicationLinkOwnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplicationLinkOwners not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Profile(ctx, req.(*QueryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IncomingDTagTransferRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncomingDTagTransferRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IncomingDTagTransferRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/IncomingDTagTransferRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IncomingDTagTransferRequests(ctx, req.(*QueryIncomingDTagTransferRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ChainLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChainLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ChainLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/ChainLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ChainLinks(ctx, req.(*QueryChainLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ChainLinkOwners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChainLinkOwnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ChainLinkOwners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/ChainLinkOwners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ChainLinkOwners(ctx, req.(*QueryChainLinkOwnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DefaultExternalAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDefaultExternalAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DefaultExternalAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/DefaultExternalAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DefaultExternalAddresses(ctx, req.(*QueryDefaultExternalAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApplicationLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApplicationLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApplicationLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/ApplicationLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApplicationLinks(ctx, req.(*QueryApplicationLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApplicationLinkByClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApplicationLinkByClientIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApplicationLinkByClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/ApplicationLinkByClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApplicationLinkByClientID(ctx, req.(*QueryApplicationLinkByClientIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApplicationLinkOwners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApplicationLinkOwnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApplicationLinkOwners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/ApplicationLinkOwners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApplicationLinkOwners(ctx, req.(*QueryApplicationLinkOwnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/desmos.profiles.v3.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "desmos.profiles.v3.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Profile",
			Handler:    _Query_Profile_Handler,
		},
		{
			MethodName: "IncomingDTagTransferRequests",
			Handler:    _Query_IncomingDTagTransferRequests_Handler,
		},
		{
			MethodName: "ChainLinks",
			Handler:    _Query_ChainLinks_Handler,
		},
		{
			MethodName: "ChainLinkOwners",
			Handler:    _Query_ChainLinkOwners_Handler,
		},
		{
			MethodName: "DefaultExternalAddresses",
			Handler:    _Query_DefaultExternalAddresses_Handler,
		},
		{
			MethodName: "ApplicationLinks",
			Handler:    _Query_ApplicationLinks_Handler,
		},
		{
			MethodName: "ApplicationLinkByClientID",
			Handler:    _Query_ApplicationLinkByClientID_Handler,
		},
		{
			MethodName: "ApplicationLinkOwners",
			Handler:    _Query_ApplicationLinkOwners_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desmos/profiles/v3/query.proto",
}
