version: '3'

services:
  desmosnode0:
    container_name: desmosnode0
    image: "desmoslabs/desmos:v0.17.2"
    command: "desmos start"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-desmos.log}
    volumes:
      - ./../../build/node0/desmos:/root/.desmos
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  desmosnode1:
    container_name: desmosnode1
    image: "desmoslabs/desmos:v0.17.2"
    command: "desmos start"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-desmos.log}
    volumes:
      - ./../../build/node1/desmos:/root/.desmos
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  desmosnode2:
    container_name: desmosnode2
    image: "desmoslabs/desmos:v0.17.2"
    command: "desmos start"
    environment:
      - ID=2
      - LOG=${LOG:-desmos.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./../../build/node2/desmos:/root/.desmos
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  desmosnode3:
    container_name: desmosnode3
    image: "desmoslabs/desmos:v0.17.2"
    command: "desmos start"
    environment:
      - ID=3
      - LOG=${LOG:-desmos.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./../../build/node3/desmos:/root/.desmos
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
