package types

// Subspaces module event types
const (
	EventTypeCreatedSubspace              = "created_subspace"
	EventTypeEditedSubspace               = "edited_subspace"
	EventTypeDeletedSubspace              = "deleted_subspace"
	EventTypeCreatedSection               = "created_section"
	EventTypeEditedSection                = "edited_section"
	EventTypeMovedSection                 = "moved_section"
	EventTypeDeletedSection               = "deleted_section"
	EventTypeCreatedUserGroup             = "created_user_group"
	EventTypeEditedUserGroup              = "edited_user_group"
	EvenTypeMovedUserGroup                = "moved_user_group"
	EventTypeSetUserGroupPermissions      = "set_user_group_permissions"
	EventTypeDeletedUserGroup             = "deleted_user_group"
	EventTypeAddedUserToGroup             = "added_group_member"
	EventTypeRemovedUserFromGroup         = "removed_group_member"
	EventTypeSetUserPermissions           = "set_user_permissions"
	EventTypeGrantedTreasuryAuthorization = "granted_treasury_authorization"
	EventTypeRevokedTreasuryAuthorization = "revoked_treasury_authorization"
	EventTypeGrantedAllowance             = "granted_allowance"
	EventTypeRevokedAllowance             = "revoked_allowance"
	EventTypeUpdatedSubspaceFeeToken      = "updated_subspace_fee_token"

	AttributeKeySubspaceID      = "subspace_id"
	AttributeKeySubspaceName    = "subspace_name"
	AttributeKeySubspaceCreator = "subspace_creator"
	AttributeKeyCreationTime    = "creation_date"
	AttributeKeySectionID       = "section_id"
	AttributeKeyUserGroupID     = "user_group_id"
	AttributeKeyPermissions     = "permissions"
	AttributeKeyUser            = "user"
	AttributeKeyGranter         = "granter"
	AttributeKeyGrantee         = "grantee"
	AttributeKeyUserGrantee     = "user_grantee"
	AttributeKeyGroupGrantee    = "group_grantee"
)
