package magpie

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/desmos-labs/desmos/x/magpie/internal/keeper"
	"github.com/desmos-labs/desmos/x/magpie/internal/simulation"
	"github.com/desmos-labs/desmos/x/magpie/internal/types"
)

const (
	ModuleName                = types.ModuleName
	RouterKey                 = types.RouterKey
	StoreKey                  = types.StoreKey
	ActionCreationSession     = types.ActionCreationSession
	EventTypeCreateSession    = types.EventTypeCreateSession
	AttributeKeySessionID     = types.AttributeKeySessionID
	AttributeKeyNamespace     = types.AttributeKeyNamespace
	AttributeKeyExternalOwner = types.AttributeKeyExternalOwner
	AttributeKeyExpiry        = types.AttributeKeyExpiry
	AttributeValueCategory    = types.AttributeValueCategory
	QuerySessions             = keeper.QuerySessions
	OpWeightMsgCreatePost     = simulation.OpWeightMsgCreatePost
)

var (
	// functions aliases
	RandomSessionData        = simulation.RandomSessionData
	WeightedOperations       = simulation.WeightedOperations
	SimulateMsgCreateSession = simulation.SimulateMsgCreateSession
	RandomizedGenState       = simulation.RandomizedGenState
	DecodeStore              = simulation.DecodeStore
	NewMsgCreateSession      = types.NewMsgCreateSession
	SessionStoreKey          = types.SessionStoreKey
	ParseSessionID           = types.ParseSessionID
	NewSession               = types.NewSession
	NewGenesisState          = types.NewGenesisState
	DefaultGenesisState      = types.DefaultGenesisState
	ValidateGenesis          = types.ValidateGenesis
	RegisterCodec            = types.RegisterCodec
	NewHandler               = keeper.NewHandler
	NewKeeper                = keeper.NewKeeper
	NewQuerier               = keeper.NewQuerier

	// variable aliases
	RandomNamespaces      = simulation.RandomNamespaces
	SessionLengthKey      = types.SessionLengthKey
	LastSessionIDStoreKey = types.LastSessionIDStoreKey
	SessionStorePrefix    = types.SessionStorePrefix
	ModuleCdc             = types.ModuleCdc
)

type (
	Keeper           = keeper.Keeper
	SessionData      = simulation.SessionData
	MsgCreateSession = types.MsgCreateSession
	SessionID        = types.SessionID
	Session          = types.Session
	Sessions         = types.Sessions
	GenesisState     = types.GenesisState
)
