// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: desmos/ibc/applications/profiles/v1/models.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/x/ibc/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State defines if a connection is in the following states:
// STARTED, ERRORED, SUCCESSFUL, TIMED_OUT
type ConnectionState int32

const (
	// Default State
	CONNECTION_STATE_UNINITIALIZED ConnectionState = 0
	// A connection has just been started
	CONNECTION_STATE_STARTED ConnectionState = 1
	// A connection has errored during the verification
	CONNECTION_STATE_ERROR ConnectionState = 2
	// A connection has been verified successfully
	CONNECTION_STATE_SUCCESS ConnectionState = 3
	// A connection has timed out during the verification
	CONNECTION_STATE_TIMEOUT ConnectionState = 4
)

var ConnectionState_name = map[int32]string{
	0: "CONNECTION_STATE_UNINITIALIZED_UNSPECIFIED",
	1: "CONNECTION_STATE_STARTED",
	2: "CONNECTION_STATE_ERROR",
	3: "CONNECTION_STATE_SUCCESS",
	4: "CONNECTION_STATE_TIMED_OUT",
}

var ConnectionState_value = map[string]int32{
	"CONNECTION_STATE_UNINITIALIZED_UNSPECIFIED": 0,
	"CONNECTION_STATE_STARTED":                   1,
	"CONNECTION_STATE_ERROR":                     2,
	"CONNECTION_STATE_SUCCESS":                   3,
	"CONNECTION_STATE_TIMED_OUT":                 4,
}

func (x ConnectionState) String() string {
	return proto.EnumName(ConnectionState_name, int32(x))
}

func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{0}
}

// ApplicationData contains the data of a generic centralized application
type ApplicationData struct {
	// The application name (eg. Twitter, GitHub, etc)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Username on the application (eg. Twitter tag, GitHub profile, etc)
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *ApplicationData) Reset()         { *m = ApplicationData{} }
func (m *ApplicationData) String() string { return proto.CompactTextString(m) }
func (*ApplicationData) ProtoMessage()    {}
func (*ApplicationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{0}
}
func (m *ApplicationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationData.Merge(m, src)
}
func (m *ApplicationData) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationData) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationData.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationData proto.InternalMessageInfo

func (m *ApplicationData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// VerificationData contains the data of a single verification
type VerificationData struct {
	// The method uses to verify the social account ownership (eg. tweet, gist,
	// etc.)
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty" yaml:"method"`
	// The value used to verify the social account ownership (eg. Twitter tweet
	// id, GitHub gist id, etc)
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
}

func (m *VerificationData) Reset()         { *m = VerificationData{} }
func (m *VerificationData) String() string { return proto.CompactTextString(m) }
func (*VerificationData) ProtoMessage()    {}
func (*VerificationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{1}
}
func (m *VerificationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationData.Merge(m, src)
}
func (m *VerificationData) XXX_Size() int {
	return m.Size()
}
func (m *VerificationData) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationData.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationData proto.InternalMessageInfo

func (m *VerificationData) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *VerificationData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Connection contains the data of a centralized social network connection
type Connection struct {
	// User that has created the connection
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Application to which the user has connected
	Application *ApplicationData `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	// Data used to verify the connection
	Verification *VerificationData `protobuf:"bytes,3,opt,name=verification,proto3" json:"verification,omitempty"`
	// State of the connection
	State ConnectionState `protobuf:"varint,4,opt,name=state,proto3,enum=desmos.ibc.applications.profiles.v1.ConnectionState" json:"state,omitempty"`
	// OracleRequest represents the request that has been made to the oracle
	OracleRequest *OracleRequest `protobuf:"bytes,5,opt,name=oracle_request,json=oracleRequest,proto3" json:"oracle_request,omitempty"`
	// Data coming from the result of the verification.
	// Only available when the state is STATE_SUCCESS
	Result *Result `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	// Creation time of the connection
	CreationTime time.Time `protobuf:"bytes,7,opt,name=creation_time,json=creationTime,proto3,stdtime" json:"creation_time"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{2}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return m.Size()
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Connection) GetApplication() *ApplicationData {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Connection) GetVerification() *VerificationData {
	if m != nil {
		return m.Verification
	}
	return nil
}

func (m *Connection) GetState() ConnectionState {
	if m != nil {
		return m.State
	}
	return CONNECTION_STATE_UNINITIALIZED
}

func (m *Connection) GetOracleRequest() *OracleRequest {
	if m != nil {
		return m.OracleRequest
	}
	return nil
}

func (m *Connection) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Connection) GetCreationTime() time.Time {
	if m != nil {
		return m.CreationTime
	}
	return time.Time{}
}

// OracleRequest represents a generic oracle request
type OracleRequest struct {
	// ID is the ID of the request
	ID int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// OracleScriptID is ID of an oracle script
	OracleScriptID int64 `protobuf:"varint,2,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty"`
	// ClientID represents the ID of the client that has called the oracle script
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *OracleRequest) Reset()         { *m = OracleRequest{} }
func (m *OracleRequest) String() string { return proto.CompactTextString(m) }
func (*OracleRequest) ProtoMessage()    {}
func (*OracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{3}
}
func (m *OracleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRequest.Merge(m, src)
}
func (m *OracleRequest) XXX_Size() int {
	return m.Size()
}
func (m *OracleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRequest proto.InternalMessageInfo

func (m *OracleRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OracleRequest) GetOracleScriptID() int64 {
	if m != nil {
		return m.OracleScriptID
	}
	return 0
}

func (m *OracleRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// Result represents a verification result
type Result struct {
	// sum is the oneof that specifies whether this represents a success or
	// failure result
	//
	// Types that are valid to be assigned to Sum:
	//	*Result_Success_
	//	*Result_Failed_
	Sum isResult_Sum `protobuf_oneof:"sum"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{4}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Result.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return m.Size()
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type isResult_Sum interface {
	isResult_Sum()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type Result_Success_ struct {
	Success *Result_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
}
type Result_Failed_ struct {
	Failed *Result_Failed `protobuf:"bytes,2,opt,name=failed,proto3,oneof" json:"failed,omitempty"`
}

func (*Result_Success_) isResult_Sum() {}
func (*Result_Failed_) isResult_Sum()  {}

func (m *Result) GetSum() isResult_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Result) GetSuccess() *Result_Success {
	if x, ok := m.GetSum().(*Result_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *Result) GetFailed() *Result_Failed {
	if x, ok := m.GetSum().(*Result_Failed_); ok {
		return x.Failed
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Result) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Result_Success_)(nil),
		(*Result_Failed_)(nil),
	}
}

// Single is the signature data for a single signer
type Result_Success struct {
	// Value that has be signed by the profile
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Signature that has been produced by signing the value
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Result_Success) Reset()         { *m = Result_Success{} }
func (m *Result_Success) String() string { return proto.CompactTextString(m) }
func (*Result_Success) ProtoMessage()    {}
func (*Result_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{4, 0}
}
func (m *Result_Success) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Result_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Result_Success.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Result_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result_Success.Merge(m, src)
}
func (m *Result_Success) XXX_Size() int {
	return m.Size()
}
func (m *Result_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Result_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Result_Success proto.InternalMessageInfo

func (m *Result_Success) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Result_Success) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// Multi is the signature data for a multisig public key
type Result_Failed struct {
	// Error that is associated with the failure
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Result_Failed) Reset()         { *m = Result_Failed{} }
func (m *Result_Failed) String() string { return proto.CompactTextString(m) }
func (*Result_Failed) ProtoMessage()    {}
func (*Result_Failed) Descriptor() ([]byte, []int) {
	return fileDescriptor_0611fef640455089, []int{4, 1}
}
func (m *Result_Failed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Result_Failed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Result_Failed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Result_Failed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result_Failed.Merge(m, src)
}
func (m *Result_Failed) XXX_Size() int {
	return m.Size()
}
func (m *Result_Failed) XXX_DiscardUnknown() {
	xxx_messageInfo_Result_Failed.DiscardUnknown(m)
}

var xxx_messageInfo_Result_Failed proto.InternalMessageInfo

func (m *Result_Failed) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("desmos.ibc.applications.profiles.v1.ConnectionState", ConnectionState_name, ConnectionState_value)
	proto.RegisterType((*ApplicationData)(nil), "desmos.ibc.applications.profiles.v1.ApplicationData")
	proto.RegisterType((*VerificationData)(nil), "desmos.ibc.applications.profiles.v1.VerificationData")
	proto.RegisterType((*Connection)(nil), "desmos.ibc.applications.profiles.v1.Connection")
	proto.RegisterType((*OracleRequest)(nil), "desmos.ibc.applications.profiles.v1.OracleRequest")
	proto.RegisterType((*Result)(nil), "desmos.ibc.applications.profiles.v1.Result")
	proto.RegisterType((*Result_Success)(nil), "desmos.ibc.applications.profiles.v1.Result.Success")
	proto.RegisterType((*Result_Failed)(nil), "desmos.ibc.applications.profiles.v1.Result.Failed")
}

func init() {
	proto.RegisterFile("desmos/ibc/applications/profiles/v1/models.proto", fileDescriptor_0611fef640455089)
}

var fileDescriptor_0611fef640455089 = []byte{
	// 842 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x25, 0x59, 0x8e, 0xc7, 0x8f, 0xa8, 0x83, 0x20, 0x10, 0xd8, 0x80, 0x14, 0xd4, 0xa2,
	0x48, 0x53, 0x94, 0xac, 0x9d, 0xb6, 0x0b, 0x23, 0x40, 0x61, 0x51, 0x4c, 0xc3, 0x22, 0x95, 0x8a,
	0x21, 0x15, 0xc0, 0xd9, 0x08, 0x7c, 0x8c, 0x95, 0x41, 0x49, 0x8d, 0xca, 0x19, 0x0a, 0xcd, 0x1f,
	0x04, 0x5e, 0xf9, 0x07, 0x8c, 0x16, 0xe8, 0xcf, 0x64, 0x99, 0x65, 0xbb, 0x51, 0x0b, 0x79, 0xd3,
	0x75, 0xbe, 0xa0, 0xe0, 0x0c, 0x59, 0x2b, 0x76, 0x14, 0xc8, 0x1b, 0xe1, 0xbe, 0xce, 0xb9, 0x77,
	0xae, 0xce, 0x05, 0xc1, 0x57, 0x11, 0x66, 0x09, 0x65, 0x26, 0x09, 0x42, 0xd3, 0x9f, 0x4e, 0x63,
	0x12, 0xfa, 0x9c, 0xd0, 0x09, 0x33, 0xa7, 0x29, 0x3d, 0x21, 0x31, 0x66, 0xe6, 0x6c, 0xdf, 0x4c,
	0x68, 0x84, 0x63, 0x66, 0x4c, 0x53, 0xca, 0x29, 0xfc, 0x44, 0x22, 0x0c, 0x12, 0x84, 0xc6, 0x32,
	0xc2, 0x28, 0x11, 0xc6, 0x6c, 0x5f, 0xbd, 0x33, 0xa6, 0x63, 0x2a, 0xea, 0xcd, 0xdc, 0x92, 0x50,
	0x55, 0x0b, 0xa9, 0x68, 0x16, 0xf8, 0x0c, 0x9b, 0xb3, 0xfd, 0x00, 0x73, 0x7f, 0xdf, 0x0c, 0x29,
	0x99, 0x14, 0x79, 0x3d, 0x9f, 0x22, 0xa4, 0x29, 0x36, 0xc3, 0x98, 0xe0, 0x09, 0xcf, 0x7b, 0x4b,
	0xab, 0x2c, 0x18, 0x53, 0x3a, 0x8e, 0xb1, 0x29, 0xbc, 0x20, 0x3b, 0x31, 0x39, 0x49, 0x30, 0xe3,
	0x7e, 0x32, 0x95, 0x05, 0x9d, 0xef, 0xc1, 0xed, 0xa3, 0xcb, 0x99, 0x7a, 0x3e, 0xf7, 0x21, 0x04,
	0xf5, 0x89, 0x9f, 0xe0, 0x96, 0xd2, 0x56, 0xee, 0x6f, 0x21, 0x61, 0x43, 0x15, 0xdc, 0xca, 0x18,
	0x4e, 0x45, 0xbc, 0x2a, 0xe2, 0xff, 0xfb, 0x87, 0xf5, 0x7f, 0x7f, 0xd7, 0x95, 0xce, 0xcf, 0xa0,
	0xf9, 0x0c, 0xa7, 0xe4, 0x64, 0x99, 0xe9, 0x73, 0xd0, 0x48, 0x30, 0x7f, 0x41, 0x23, 0xc9, 0xd5,
	0xfd, 0xe8, 0xed, 0x5c, 0xdf, 0x7d, 0xe9, 0x27, 0xf1, 0x61, 0x47, 0xc6, 0x3b, 0xa8, 0x28, 0x80,
	0x9f, 0x81, 0x8d, 0x99, 0x1f, 0x67, 0x05, 0x7b, 0xb7, 0xf9, 0x76, 0xae, 0xef, 0xc8, 0x4a, 0x11,
	0xee, 0x20, 0x99, 0x2e, 0x9a, 0x9d, 0xd5, 0x01, 0xb0, 0xe8, 0x64, 0x82, 0xc3, 0xbc, 0x57, 0x3e,
	0x71, 0x3e, 0x4d, 0x39, 0x71, 0x6e, 0xc3, 0x67, 0x60, 0x7b, 0x69, 0xd9, 0x82, 0x76, 0xfb, 0xe0,
	0x6b, 0x63, 0x8d, 0xff, 0xc2, 0xb8, 0xb2, 0x10, 0xb4, 0x4c, 0x04, 0x8f, 0xc1, 0xce, 0x6c, 0xe9,
	0x9d, 0xad, 0x9a, 0x20, 0xfe, 0x66, 0x2d, 0xe2, 0xab, 0x0b, 0x42, 0xef, 0x50, 0xc1, 0x1f, 0xc0,
	0x06, 0xe3, 0x3e, 0xc7, 0xad, 0x7a, 0x5b, 0xb9, 0xbf, 0xb7, 0xe6, 0xb0, 0x97, 0x6b, 0x70, 0x73,
	0x2c, 0x92, 0x14, 0xf0, 0x18, 0xec, 0xd1, 0xd4, 0x0f, 0x63, 0x3c, 0x4a, 0xf1, 0x2f, 0x19, 0x66,
	0xbc, 0xb5, 0x21, 0x06, 0x3d, 0x58, 0x8b, 0x74, 0x20, 0xa0, 0x48, 0x22, 0xd1, 0x2e, 0x5d, 0x76,
	0xa1, 0x05, 0x1a, 0x29, 0x66, 0x59, 0xcc, 0x5b, 0x0d, 0x41, 0xf9, 0xc5, 0x5a, 0x94, 0x48, 0x40,
	0x50, 0x01, 0x85, 0x0e, 0xd8, 0x0d, 0x53, 0x2c, 0xea, 0x46, 0xb9, 0x26, 0x5b, 0x9b, 0x82, 0x4b,
	0x35, 0xa4, 0x60, 0x8d, 0x52, 0xb0, 0x86, 0x57, 0x0a, 0xb6, 0x7b, 0xeb, 0xf5, 0x5c, 0xaf, 0x9c,
	0xfd, 0xad, 0x2b, 0x68, 0xa7, 0x84, 0xe6, 0xc9, 0x42, 0x12, 0xaf, 0x14, 0xb0, 0xfb, 0xce, 0xd8,
	0xf0, 0x2e, 0xa8, 0x12, 0xa9, 0xbc, 0x5a, 0xb7, 0xb1, 0x98, 0xeb, 0x55, 0xa7, 0x87, 0xaa, 0x24,
	0x82, 0x8f, 0x40, 0xb3, 0x58, 0x0d, 0x0b, 0x53, 0x32, 0xe5, 0x23, 0x12, 0x09, 0x79, 0xd4, 0xba,
	0x70, 0x31, 0xd7, 0xf7, 0x24, 0x89, 0x2b, 0x52, 0x4e, 0x0f, 0x15, 0x6b, 0x2c, 0xfc, 0x08, 0x7e,
	0x0c, 0xb6, 0xe4, 0x85, 0xe5, 0xb0, 0x9a, 0x3c, 0x05, 0x19, 0x70, 0xa2, 0x62, 0x94, 0xdf, 0xaa,
	0xa0, 0x21, 0x9f, 0x0b, 0x07, 0x60, 0x93, 0x65, 0x61, 0x88, 0x19, 0x13, 0x83, 0x6c, 0x1f, 0x3c,
	0xbc, 0xc1, 0xb2, 0x0c, 0x57, 0x42, 0x9f, 0x54, 0x50, 0xc9, 0x02, 0x9f, 0x82, 0xc6, 0x89, 0x4f,
	0x62, 0x1c, 0x15, 0x8a, 0x3e, 0xb8, 0x09, 0xdf, 0x63, 0x81, 0x7c, 0x52, 0x41, 0x05, 0x87, 0x6a,
	0x81, 0xcd, 0xa2, 0x07, 0xbc, 0x53, 0x1e, 0xa0, 0x3c, 0x22, 0xe9, 0xc0, 0x7b, 0x60, 0x8b, 0x91,
	0xf1, 0xc4, 0xe7, 0x59, 0x5a, 0x1e, 0xfe, 0x65, 0x40, 0x3e, 0x57, 0xfd, 0x14, 0x34, 0x24, 0x71,
	0xce, 0x81, 0xd3, 0x94, 0x96, 0x87, 0x28, 0x1d, 0x59, 0x25, 0x7f, 0xbb, 0x1b, 0xa0, 0xc6, 0xb2,
	0xe4, 0xc1, 0x5f, 0x55, 0x70, 0xfb, 0x8a, 0x70, 0x21, 0x02, 0x0f, 0xac, 0x41, 0xbf, 0x6f, 0x5b,
	0x9e, 0x33, 0xe8, 0x8f, 0x5c, 0xef, 0xc8, 0xb3, 0x47, 0xc3, 0xbe, 0xd3, 0x77, 0x3c, 0xe7, 0xe8,
	0xa9, 0xf3, 0xdc, 0xee, 0x8d, 0x86, 0x7d, 0xf7, 0x27, 0xdb, 0x72, 0x1e, 0x3b, 0x76, 0xaf, 0x59,
	0x51, 0x3b, 0xa7, 0xe7, 0x6d, 0xed, 0xc3, 0x08, 0x78, 0x08, 0x5a, 0xd7, 0x2a, 0x5c, 0xef, 0x08,
	0x79, 0x76, 0xaf, 0xa9, 0xa8, 0xf7, 0x4e, 0xcf, 0xdb, 0x2b, 0xf3, 0xf0, 0x5b, 0x70, 0xf7, 0x5a,
	0xce, 0x46, 0x68, 0x80, 0x9a, 0x55, 0x55, 0x3d, 0x3d, 0x6f, 0xaf, 0xc8, 0xbe, 0xbf, 0xe7, 0xd0,
	0xb2, 0x6c, 0xd7, 0x6d, 0xd6, 0x56, 0xf5, 0x94, 0x79, 0xf8, 0x08, 0xa8, 0xd7, 0x72, 0x9e, 0xf3,
	0xa3, 0xdd, 0x1b, 0x0d, 0x86, 0x5e, 0xb3, 0xbe, 0x02, 0x9d, 0x57, 0x0c, 0x86, 0x9e, 0x5a, 0x7f,
	0xf5, 0x87, 0x56, 0xe9, 0x1e, 0xbf, 0x5e, 0x68, 0xca, 0x9b, 0x85, 0xa6, 0xfc, 0xb3, 0xd0, 0x94,
	0xb3, 0x0b, 0xad, 0xf2, 0xe6, 0x42, 0xab, 0xfc, 0x79, 0xa1, 0x55, 0x9e, 0x7f, 0x37, 0x26, 0xfc,
	0x45, 0x16, 0x18, 0x21, 0x4d, 0x4c, 0xa9, 0x9a, 0x2f, 0x63, 0x3f, 0x60, 0x85, 0x6d, 0xfe, 0xfa,
	0x81, 0x6f, 0x1a, 0x7f, 0x39, 0xc5, 0x2c, 0x68, 0x88, 0xab, 0x7c, 0xf8, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x67, 0xb4, 0xc5, 0x06, 0x04, 0x07, 0x00, 0x00,
}

func (this *ApplicationData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ApplicationData)
	if !ok {
		that2, ok := that.(ApplicationData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	return true
}
func (this *VerificationData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VerificationData)
	if !ok {
		that2, ok := that.(VerificationData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Method != that1.Method {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *Connection) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Connection)
	if !ok {
		that2, ok := that.(Connection)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.User != that1.User {
		return false
	}
	if !this.Application.Equal(that1.Application) {
		return false
	}
	if !this.Verification.Equal(that1.Verification) {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if !this.OracleRequest.Equal(that1.OracleRequest) {
		return false
	}
	if !this.Result.Equal(that1.Result) {
		return false
	}
	if !this.CreationTime.Equal(that1.CreationTime) {
		return false
	}
	return true
}
func (this *OracleRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OracleRequest)
	if !ok {
		that2, ok := that.(OracleRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.OracleScriptID != that1.OracleScriptID {
		return false
	}
	if this.ClientId != that1.ClientId {
		return false
	}
	return true
}
func (this *Result) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Result)
	if !ok {
		that2, ok := that.(Result)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.Sum == nil {
		if this.Sum != nil {
			return false
		}
	} else if this.Sum == nil {
		return false
	} else if !this.Sum.Equal(that1.Sum) {
		return false
	}
	return true
}
func (this *Result_Success_) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Result_Success_)
	if !ok {
		that2, ok := that.(Result_Success_)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Success.Equal(that1.Success) {
		return false
	}
	return true
}
func (this *Result_Failed_) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Result_Failed_)
	if !ok {
		that2, ok := that.(Result_Failed_)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Failed.Equal(that1.Failed) {
		return false
	}
	return true
}
func (this *Result_Success) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Result_Success)
	if !ok {
		that2, ok := that.(Result_Success)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if this.Signature != that1.Signature {
		return false
	}
	return true
}
func (this *Result_Failed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Result_Failed)
	if !ok {
		that2, ok := that.(Result_Failed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (m *ApplicationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerificationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Connection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Connection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Connection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreationTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintModels(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.OracleRequest != nil {
		{
			size, err := m.OracleRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.State != 0 {
		i = encodeVarintModels(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x20
	}
	if m.Verification != nil {
		{
			size, err := m.Verification.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Application != nil {
		{
			size, err := m.Application.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintModels(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintModels(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.OracleScriptID != 0 {
		i = encodeVarintModels(dAtA, i, uint64(m.OracleScriptID))
		i--
		dAtA[i] = 0x10
	}
	if m.ID != 0 {
		i = encodeVarintModels(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Result) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Result) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Result) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Result_Success_) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Result_Success_) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Success != nil {
		{
			size, err := m.Success.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *Result_Failed_) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Result_Failed_) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Failed != nil {
		{
			size, err := m.Failed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintModels(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *Result_Success) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Result_Success) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Result_Success) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Result_Failed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Result_Failed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Result_Failed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintModels(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModels(dAtA []byte, offset int, v uint64) int {
	offset -= sovModels(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApplicationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}

func (m *VerificationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}

func (m *Connection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	if m.Application != nil {
		l = m.Application.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	if m.Verification != nil {
		l = m.Verification.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovModels(uint64(m.State))
	}
	if m.OracleRequest != nil {
		l = m.OracleRequest.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreationTime)
	n += 1 + l + sovModels(uint64(l))
	return n
}

func (m *OracleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovModels(uint64(m.ID))
	}
	if m.OracleScriptID != 0 {
		n += 1 + sovModels(uint64(m.OracleScriptID))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}

func (m *Result) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *Result_Success_) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success != nil {
		l = m.Success.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}
func (m *Result_Failed_) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Failed != nil {
		l = m.Failed.Size()
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}
func (m *Result_Success) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}

func (m *Result_Failed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovModels(uint64(l))
	}
	return n
}

func sovModels(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModels(x uint64) (n int) {
	return sovModels(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApplicationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Connection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Connection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Connection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Application", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Application == nil {
				m.Application = &ApplicationData{}
			}
			if err := m.Application.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Verification == nil {
				m.Verification = &VerificationData{}
			}
			if err := m.Verification.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= ConnectionState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OracleRequest == nil {
				m.OracleRequest = &OracleRequest{}
			}
			if err := m.OracleRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &Result{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptID", wireType)
			}
			m.OracleScriptID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Result) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Result: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Result: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Result_Success{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Result_Success_{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Failed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Result_Failed{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Result_Failed_{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Result_Success) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Success: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Success: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Result_Failed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModels
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Failed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Failed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModels
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModels
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModels
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModels(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModels
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModels(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModels
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModels
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModels
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModels
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModels
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModels
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModels        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModels          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModels = fmt.Errorf("proto: unexpected end of group")
)
